# Generated by Django 5.0 on 2023-12-19 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apis_entities", "0001_initial"),
        ("apis_metainfo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventWork",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="InstitutionEvent",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="InstitutionInstitution",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="InstitutionPlace",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="InstitutionWork",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="PersonEvent",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="PersonInstitution",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="PersonPerson",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="PersonPlace",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="PersonWork",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="PlaceEvent",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="PlacePlace",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="PlaceWork",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="WorkWork",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="EventEvent",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
                (
                    "related_eventa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_eventb",
                        to="apis_entities.event",
                    ),
                ),
                (
                    "related_eventb",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_eventa",
                        to="apis_entities.event",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
    ]
