# Generated by Django 5.0.1 on 2024-03-01 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_relations", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventevent",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="eventwork",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="institutionevent",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="institutioninstitution",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="institutionplace",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="institutionwork",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="personevent",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="personinstitution",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="personperson",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="personplace",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="personwork",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="placeevent",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="placeplace",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="placework",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="workwork",
            options={
                "default_manager_name": "objects",
                "ordering": ["start_date", "id"],
            },
        ),
    ]
