replicaCount: 1
image:
    repository: $repository
    tag: "$tag"
    pullPolicy: Always
    secrets: []
extraLabels:
    "ID": "$service_id"
gitlab:
    app: "$app_name"
    envURL: "$repo_url"
service:
    enabled: true
    name: "web"
    url: "$public_url"
    type: ClusterIP
    externalPort: 8020 # the port your app runs on
    internalPort: 8020 # the port your app runs on
ingress:
    enabled: true
    path: "/"
    className: "nginx"
    annotations:
        #nginx.ingress.kubernetes.io/app-root: # the root route if it is not /
startupProbe:
  enabled: true
  probeType: "httpGet"
  path: /export/
  failureThreshold: 60
  periodSeconds: 10
  timeoutSeconds: 10
  initialDelaySeconds: 15

livenessProbe:
  enabled: true
  probeType: "httpGet"
  path: /export/ # lightweight — just "is eXist running?"
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 5

readinessProbe:
  enabled: true
  probeType: "httpGet"
  path: / # actual API check
  port: 8020
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
