# Generated by Django 5.0 on 2023-12-19 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apis_metainfo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="The persons´s forename. In case of more then one name...",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "female"),
                            ("male", "male"),
                            ("third gender", "third gender"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
                (
                    "lat",
                    models.FloatField(blank=True, null=True, verbose_name="latitude"),
                ),
                (
                    "lng",
                    models.FloatField(blank=True, null=True, verbose_name="longitude"),
                ),
            ],
            options={
                "ordering": ["id"],
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "tempentityclass_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="apis_metainfo.tempentityclass",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
            bases=("apis_metainfo.tempentityclass",),
        ),
    ]
