# Generated by Django 5.2.7 on 2025-10-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_entities",
            "0004_alter_event_options_alter_institution_options_and_more",
        ),
        (
            "apis_relations",
            "0003_alter_eventevent_options_alter_eventwork_options_and_more",
        ),
        ("apis_vocabularies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="eventb_relationtype_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="eventa_set",
                through="apis_relations.EventEvent",
                through_fields=("related_eventa", "relation_type"),
                to="apis_vocabularies.eventeventrelation",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="eventb_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="eventa_set",
                through="apis_relations.EventEvent",
                through_fields=("related_eventa", "related_eventb"),
                to="apis_entities.event",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="institutionb_relationtype_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="institutiona_set",
                through="apis_relations.InstitutionInstitution",
                through_fields=("related_institutiona", "relation_type"),
                to="apis_vocabularies.institutioninstitutionrelation",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="institutionb_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="institutiona_set",
                through="apis_relations.InstitutionInstitution",
                through_fields=("related_institutiona", "related_institutionb"),
                to="apis_entities.institution",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="personb_relationtype_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="persona_set",
                through="apis_relations.PersonPerson",
                through_fields=("related_persona", "relation_type"),
                to="apis_vocabularies.personpersonrelation",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="personb_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="persona_set",
                through="apis_relations.PersonPerson",
                through_fields=("related_persona", "related_personb"),
                to="apis_entities.person",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="placeb_relationtype_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="placea_set",
                through="apis_relations.PlacePlace",
                through_fields=("related_placea", "relation_type"),
                to="apis_vocabularies.placeplacerelation",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="placeb_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="placea_set",
                through="apis_relations.PlacePlace",
                through_fields=("related_placea", "related_placeb"),
                to="apis_entities.place",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="workb_relationtype_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="worka_set",
                through="apis_relations.WorkWork",
                through_fields=("related_worka", "relation_type"),
                to="apis_vocabularies.workworkrelation",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="workb_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="worka_set",
                through="apis_relations.WorkWork",
                through_fields=("related_worka", "related_workb"),
                to="apis_entities.work",
            ),
        ),
    ]
