# Generated by Django 5.1.1 on 2024-11-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="edge",
            options={
                "ordering": ["-id"],
                "verbose_name": "Kante",
                "verbose_name_plural": "Kanten",
            },
        ),
        migrations.AlterField(
            model_name="edge",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("person", "Person"),
                    ("institution", "Institution"),
                    ("place", "Ort"),
                    ("event", "Ereignis"),
                    ("work", "Werk"),
                ],
                help_text="Art der Quelle (Person, Ort, Werk, Institution, Ereignis)",
                max_length=250,
                verbose_name="Art der Quelle",
            ),
        ),
        migrations.AlterField(
            model_name="edge",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("person", "Person"),
                    ("institution", "Institution"),
                    ("place", "Ort"),
                    ("event", "Ereignis"),
                    ("work", "Werk"),
                ],
                help_text="Art des Ziels (Person, Ort, Werk, Institution, Ereignis)",
                max_length=250,
                verbose_name="Art des Ziels",
            ),
        ),
    ]
