# Generated by Django 5.0 on 2023-12-19 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apis_metainfo", "0001_initial"),
        ("apis_vocabularies", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="collection_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apis_vocabularies.collectiontype",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="groups_allowed",
            field=models.ManyToManyField(to="auth.group"),
        ),
        migrations.AddField(
            model_name="collection",
            name="parent_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apis_metainfo.collection",
            ),
        ),
        migrations.AddField(
            model_name="tempentityclass",
            name="collection",
            field=models.ManyToManyField(to="apis_metainfo.collection"),
        ),
        migrations.AddField(
            model_name="tempentityclass",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apis_metainfo.source",
            ),
        ),
        migrations.AddField(
            model_name="text",
            name="kind",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apis_vocabularies.texttype",
            ),
        ),
        migrations.AddField(
            model_name="text",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apis_metainfo.source",
            ),
        ),
        migrations.AddField(
            model_name="tempentityclass",
            name="text",
            field=models.ManyToManyField(blank=True, to="apis_metainfo.text"),
        ),
        migrations.AddField(
            model_name="uri",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Entität die mit dieser URI verbunden ist",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apis_metainfo.tempentityclass",
                verbose_name="Entität",
            ),
        ),
    ]
