# Generated by Django 5.0.1 on 2024-01-20 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_metainfo", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempentityclass",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="angelegt",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tempentityclass",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="zuletzt geändert"),
        ),
    ]
