# Generated by Django 5.0.1 on 2024-01-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_metainfo", "0003_tempentityclass_created_tempentityclass_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempentityclass",
            name="img_last_checked",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="geprüft am",
                help_text="Datum an dem die Bild-URL eingetragen wurde."
            ),
        ),
        migrations.AddField(
            model_name="tempentityclass",
            name="img_url",
            field=models.URLField(
                blank=True,
                help_text="URL zu einem Bild der Entität",
                null=True,
                max_length=300,
                verbose_name="Bild URL",
            ),
        ),
    ]
