# Generated by Django 5.2.7 on 2025-10-29 06:53

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_metainfo", "0004_tempentityclass_img_last_checked_and_more"),
        ("apis_vocabularies", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="collection_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Setze 'Projekt' damit das Projekt unter '/projects' aufscheint",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apis_vocabularies.collectiontype",
                verbose_name="Typ des Projektes",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Kurze Beschreibung des Projektes, der Sammlung",
                verbose_name="Beschreibung",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="groups_allowed",
            field=models.ManyToManyField(
                blank=True, to="auth.group", verbose_name="bitte ignorieren"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(
                help_text="Name des Projektes, der Sammlung",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="parent_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apis_metainfo.collection",
                verbose_name="bitte ignorieren",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="published",
            field=models.BooleanField(
                default=False,
                help_text="Auf 'True' setzen damit das Projekt unter 'projects' aufscheint.",
                verbose_name="veröffentlicht",
            ),
        ),
    ]
