# Generated by Django 5.2.7 on 2026-08-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0005_alter_collection_collection_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='groups_allowed',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='parent_class',
        ),
        migrations.AlterField(
            model_name='tempentityclass',
            name='img_last_checked',
            field=models.DateTimeField(blank=True, help_text='Datum an dem die Bild-URL eingetragen wurde.', null=True, verbose_name='Bild geprüft am'),
        ),
    ]
