# Generated by Django 5.2.7 on 2026-08-27 07:48

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0006_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='related_domain',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), blank=True, default=list, help_text='URIs bzw. Domains, die mit diesem Projekt verbunden sind.', size=None, verbose_name='Verknüpfte URI-Domains'),
        ),
    ]
