# Generated by Django 5.2.7 on 2025-10-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_entities", "0005_alter_event_eventb_relationtype_set_and_more"),
        (
            "apis_relations",
            "0003_alter_eventevent_options_alter_eventwork_options_and_more",
        ),
        ("apis_vocabularies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventeventrelation",
            name="eventb_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="eventa_relationtype_set",
                through="apis_relations.EventEvent",
                through_fields=("relation_type", "related_eventb"),
                to="apis_entities.event",
            ),
        ),
        migrations.AlterField(
            model_name="institutioninstitutionrelation",
            name="institutionb_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="institutiona_relationtype_set",
                through="apis_relations.InstitutionInstitution",
                through_fields=("relation_type", "related_institutionb"),
                to="apis_entities.institution",
            ),
        ),
        migrations.AlterField(
            model_name="personpersonrelation",
            name="personb_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="persona_relationtype_set",
                through="apis_relations.PersonPerson",
                through_fields=("relation_type", "related_personb"),
                to="apis_entities.person",
            ),
        ),
        migrations.AlterField(
            model_name="placeplacerelation",
            name="placeb_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="placea_relationtype_set",
                through="apis_relations.PlacePlace",
                through_fields=("relation_type", "related_placeb"),
                to="apis_entities.place",
            ),
        ),
        migrations.AlterField(
            model_name="workworkrelation",
            name="workb_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="worka_relationtype_set",
                through="apis_relations.WorkWork",
                through_fields=("relation_type", "related_workb"),
                to="apis_entities.work",
            ),
        ),
    ]
