name: Test
on: 
  push:
jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: github_actions
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
    - name: install dependencies
      run: uv sync --locked
    - name: Run migrations
      run: |
        export NEW_PMB=TRUE
        uv run manage.py migrate
        unset NEW_PMB
    - name: Run tests
      run: uv runcoverage run manage.py test -v 3
    - name: Create Coverage Report
      run: uv run coverage xml
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.xml
        fail_ci_if_error: false
